-- LEGEND: Roads of Ashmere
-- Supabase traveler cloud-slot storage
-- Run this once in the Supabase SQL Editor.

create table if not exists public.traveler_slots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slot smallint not null check (slot between 1 and 2),
  display_name text not null default 'Unnamed Traveler',
  traveler_data jsonb not null,
  updated_at timestamptz not null default now(),
  constraint traveler_slots_user_slot_unique unique (user_id, slot)
);

alter table public.traveler_slots enable row level security;

drop policy if exists "Users can view their own traveler slots" on public.traveler_slots;
create policy "Users can view their own traveler slots"
  on public.traveler_slots for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own traveler slots" on public.traveler_slots;
create policy "Users can insert their own traveler slots"
  on public.traveler_slots for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own traveler slots" on public.traveler_slots;
create policy "Users can update their own traveler slots"
  on public.traveler_slots for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own traveler slots" on public.traveler_slots;
create policy "Users can delete their own traveler slots"
  on public.traveler_slots for delete
  using (auth.uid() = user_id);

create index if not exists traveler_slots_user_id_idx on public.traveler_slots(user_id);
