// LEGEND v0.9.4 - Beginning, traveler identity, and guided intro layer
(()=>{
  const ROOT=()=>document.getElementById('root');
  const D=()=>window.LEGEND_DATA||{};
  const S=()=>window.LegendStorage||{};
  const CONTINUE_KEY='legend-v094-continue-after-create';
  const state={name:'',gender:null,personality:null,origin:null,className:null,keepsake:null};
  const genderOptions=[
    {id:'woman',label:'Woman',pronouns:'she/her',text:'Ashmere reads you as a woman of the road. Flavor only.'},
    {id:'man',label:'Man',pronouns:'he/him',text:'Ashmere reads you as a man of the road. Flavor only.'},
    {id:'nonbinary',label:'Nonbinary',pronouns:'they/them',text:'Ashmere reads you as neither one thing nor another. Flavor only.'},
    {id:'unspoken',label:'Keep It Unspoken',pronouns:'they/them',text:'Ashmere learns your name first. The rest can stay yours.'}
  ];
  const personalityOptions=[
    {id:'kind',label:'Kind-Hearted',tag:'+1 luck',bonus:{luck:1},text:'You notice fear before weakness.'},
    {id:'grim',label:'Grim Survivor',tag:'+1 survival',bonus:{survival:1},text:'You expect the worst and prepare for it.'},
    {id:'bold',label:'Bold Wanderer',tag:'+1 strength',bonus:{strength:1},text:'You step forward before doubt gets a vote.'},
    {id:'clever',label:'Clever Talker',tag:'+1 lore',bonus:{lore:1},text:'You listen for what people almost say.'},
    {id:'quiet',label:'Quiet Watcher',tag:'+1 thieving',bonus:{thieving:1},text:'You survive by noticing what others miss.'}
  ];
  function esc(s){return String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function gender(id){return genderOptions.find(x=>x.id===id)||genderOptions[3];}
  function personality(id){return personalityOptions.find(x=>x.id===id)||personalityOptions[0];}
  function wrap(html){const r=ROOT();if(!r)return;r.innerHTML='<main class="v094-beginning"><div class="v094-beginning-bg" aria-hidden="true"></div><div class="v094-beginning-shell">'+html+'</div></main>';}
  function buttons(back,next,label='Continue'){return '<div class="v094-actions">'+(next?'<button class="v094-btn primary" id="v094Next">'+esc(label)+'</button>':'')+(back?'<button class="v094-btn" id="v094Back">Back</button>':'')+'</div>';}
  function choices(items,key){return '<div class="v094-choice-grid">'+items.map(x=>'<button class="v094-choice" data-'+key+'="'+esc(x.id)+'"><strong>'+esc(x.label)+'</strong><span>'+esc(x.text||'')+'</span>'+(x.tag?'<em>'+esc(x.tag)+'</em>':'')+'</button>').join('')+'</div>';}
  function startCreation(){state.name='';state.gender=null;state.personality=null;state.origin=null;state.className=null;state.keepsake=null;renderName();}
  function renderName(){wrap('<section class="v094-beginning-card"><div class="v094-kicker">Traveler Creation</div><h1>Who reaches Ashmere?</h1><p>You wake under a dead lantern with road mud on your boots. Give the town a name to remember.</p><div class="v094-field"><label for="v094Name">Traveler Name</label><input id="v094Name" maxlength="24" placeholder="Name, no spaces" value="'+esc(state.name)+'"></div>'+buttons(true,true,'Choose Identity')+'</section>');document.getElementById('v094Back').onclick=()=>location.reload();document.getElementById('v094Next').onclick=()=>{const n=document.getElementById('v094Name').value.trim();if(!n||/\s/.test(n))return alert('Name cannot be empty or contain spaces.');state.name=n;renderGender();};}
  function renderGender(){wrap('<section class="v094-beginning-card"><div class="v094-kicker">Identity</div><h2>How does Ashmere know you?</h2><p>This adds personality to your traveler. It does not lock your build.</p>'+choices(genderOptions,'gender')+buttons(true,false)+'</section>');document.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>{state.gender=b.dataset.gender;renderPersonality();});document.getElementById('v094Back').onclick=renderName;}
  function renderPersonality(){wrap('<section class="v094-beginning-card"><div class="v094-kicker">Personality</div><h2>What survived with you?</h2><p>Your personality gives a small starting modifier and helps the game describe your traveler.</p>'+choices(personalityOptions,'personality')+buttons(true,false)+'</section>');document.querySelectorAll('[data-personality]').forEach(b=>b.onclick=()=>{state.personality=b.dataset.personality;renderOrigin();});document.getElementById('v094Back').onclick=renderGender;}
  function renderOrigin(){const items=Object.entries(D().origins||{}).map(([id,d])=>({id,label:id,text:d.text,tag:Object.entries(d.bonus||{}).map(([k,v])=>'+'+v+' '+k).join(', ')}));wrap('<section class="v094-beginning-card"><div class="v094-kicker">Origin</div><h2>Who were you before?</h2><p>The Old Road did not create you. It only found what was already there.</p>'+choices(items,'origin')+buttons(true,false)+'</section>');document.querySelectorAll('[data-origin]').forEach(b=>b.onclick=()=>{state.origin=b.dataset.origin;renderClass();});document.getElementById('v094Back').onclick=renderPersonality;}
  function renderClass(){const items=Object.entries(D().classes||{}).map(([id,d])=>({id,label:id,text:d.desc,tag:'HP '+d.hp+' • '+d.move}));wrap('<section class="v094-beginning-card"><div class="v094-kicker">Class</div><h2>How do you survive?</h2><p>Your class sets your starting HP, gold, and first combat identity.</p>'+choices(items,'class')+buttons(true,false)+'</section>');document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{state.className=b.dataset.class;renderKeepsake();});document.getElementById('v094Back').onclick=renderOrigin;}
  function renderKeepsake(){const items=Object.entries(D().keepsakes||{}).map(([id,d])=>({id,label:id,text:d.text,tag:Object.entries(d.bonus||{}).map(([k,v])=>'+'+v+' '+k).join(', ')}));wrap('<section class="v094-beginning-card"><div class="v094-kicker">Keepsake</div><h2>What did you keep?</h2><p>One thing came with you from before Ashmere.</p>'+choices(items,'keepsake')+buttons(true,false)+'</section>');document.querySelectorAll('[data-keepsake]').forEach(b=>b.onclick=()=>{state.keepsake=b.dataset.keepsake;renderConfirm();});document.getElementById('v094Back').onclick=renderClass;}
  function renderConfirm(){const g=gender(state.gender),pers=personality(state.personality);wrap('<section class="v094-beginning-card"><div class="v094-kicker">Confirm Traveler</div><h2>'+esc(state.name)+'</h2><p>A '+esc(pers.label.toLowerCase())+' traveler reaches Ashmere. The bell is silent. The gate is open.</p><div class="v094-summary"><div><span>Gender</span><strong>'+esc(g.label)+' ('+esc(g.pronouns)+')</strong></div><div><span>Personality</span><strong>'+esc(pers.label)+'</strong></div><div><span>Origin</span><strong>'+esc(state.origin)+'</strong></div><div><span>Class</span><strong>'+esc(state.className)+'</strong></div><div><span>Keepsake</span><strong>'+esc(state.keepsake)+'</strong></div></div>'+buttons(true,true,'Begin the Road')+'</section>');document.getElementById('v094Back').onclick=renderKeepsake;document.getElementById('v094Next').onclick=createTraveler;}
  function makePlayer(){const cls=D().classes[state.className],org=D().origins[state.origin],keep=D().keepsakes[state.keepsake],pers=personality(state.personality),g=gender(state.gender);const inv={gmail:0,hbone:0,rtab:0,food:2,rfood:0,bait:0,potion:1,camp:1,fur:0,gem:0,log:0,ore:0,morb:0,codeFragment:0,bellFragment:0,roadToken:0};Object.entries(org.items||{}).forEach(([k,v])=>inv[k]=(inv[k]||0)+v);Object.entries(keep.items||{}).forEach(([k,v])=>inv[k]=(inv[k]||0)+v);const base={version:D().VERSION,username:state.name,gender:g.id,genderLabel:g.label,pronouns:g.pronouns,personality:pers.id,personalityLabel:pers.label,creationV094:{gender:g,personality:pers,bonuses:pers.bonus||{}},world:'Eldermere',town:'Ashmere',origin:state.origin,className:state.className,keepsake:state.keepsake,level:1,hp:cls.hp,maxHp:cls.hp,xp:0,xpUntil:420,gold:cls.gold+(org.gold||0),weapon:'hand',armor:'none',ownedWeapons:{hand:1},ownedArmor:{none:1},inventory:inv,bank:[0,0,0,0,0],stats:{},flags:{introV094Complete:false,tutorialStep:'people'},traits:[pers.label],momentum:0,skills:S().baseSkills?.()||{},mastery:{},questLog:['Ashmere Welcome: Speak to someone in the Town Square.','Old Road Proof: Prepare in town, travel the Old Road, and return with Road Tokens.'],memories:['You woke beneath a dead lantern outside Ashmere.','Identity: '+g.label+', '+g.pronouns+'.','Personality: '+pers.label+'. '+pers.text,'Origin: '+state.origin+'. '+org.text,'Keepsake: '+state.keepsake+'. '+keep.text]};return S().normalize?S().normalize(base):base;}
  function createTraveler(){const pl=makePlayer();S().savePlayer?.(pl);renderIntro(pl);}
  function renderIntro(pl){wrap('<section class="v094-beginning-card"><div class="v094-kicker">The Road to Ashmere</div><h2>The bell rings once.</h2><div class="v094-intro-lines"><p>You wake beneath a dead lantern with no memory of the last mile.</p><p>Behind you, the Old Road has folded into fog. Ahead, Ashmere burns with tired yellow light.</p><p>A guard sees your face, then the mud on your boots. He does not ask where you came from.</p><p>Inside the gate, three choices matter first: speak to the townsfolk, prepare supplies, and only then test the road.</p></div><div class="v094-summary"><div><span>First Goal</span><strong>Talk in Town Square</strong></div><div><span>Then</span><strong>Prepare at Inn / Shops</strong></div><div><span>Then</span><strong>Travel the Old Road</strong></div></div>'+buttons(false,true,'Enter Ashmere')+'</section>');document.getElementById('v094Next').onclick=()=>{const fresh=S().loadPlayer?.()||pl;fresh.flags=fresh.flags||{};fresh.flags.introV094Complete=true;fresh.flags.tutorialStep='people';S().savePlayer?.(fresh);sessionStorage.setItem(CONTINUE_KEY,'1');location.reload();};}
  document.addEventListener('click',e=>{const btn=e.target?.closest?.('button,.v089-menu-btn');if(!btn)return;const t=(btn.textContent||'').toLowerCase();if(t.includes('new recovered save')||t.includes('new save')||t.includes('new traveler')){e.preventDefault();e.stopPropagation();startCreation();}},true);
  function relabel(){document.querySelectorAll('button,.v089-menu-btn').forEach(btn=>{if(/New Recovered Save/i.test(btn.textContent||'')){const span=btn.querySelector('span');if(span)span.textContent='New Traveler';else btn.textContent='New Traveler';}});}setInterval(relabel,900);relabel();
  if(sessionStorage.getItem(CONTINUE_KEY)==='1'){let tries=0;const timer=setInterval(()=>{tries++;const btn=document.getElementById('continue');if(btn){sessionStorage.removeItem(CONTINUE_KEY);clearInterval(timer);btn.click();}if(tries>40)clearInterval(timer);},100);}
  window.LegendBeginningV094={startCreation,renderIntro};
})();
